stages:
    - build
    - test

# Create virtual env and install dependencies
build:
    image: python:3.7
    stage: build
    script:
        - python3 -m venv venv
        - . venv/bin/activate
        - pip install -r requirements.txt

# Run linter and tests
test
    image: python:3.7
    stage: test
    script:
        - . venv/bin/activate
        - flake8 --exclude=venv* --statistics
        - pytest -v --cov=calculator